Add files via upload

diff --git a/devfile.yaml b/devfile.yaml
--- a/devfile.yaml
+++ b/devfile.yaml
@@ -52,9 +52,9 @@ commands:
             python3 -m venv /projects/.venv || true
             . /projects/.venv/bin/activate 2>/dev/null || true
             python -m pip install --upgrade pip wheel setuptools || true
-            if [ -f requirements.txt ]; then
+            if [ -f /projects/redhat-devspaces/requirements.txt ]; then
               echo "Installing from requirements.txt ..."
-              pip install -r requirements.txt || echo "[WARN] pip install failed (see above)."
+              pip install -r /projects/redhat-devspaces/requirements.txt || echo "[WARN] pip install failed (see above)."
             else
               echo "requirements.txt not found; skipping."
             fi
@@ -79,11 +79,11 @@ commands:
       commandLine: |
         bash -lc '
           set -euxo pipefail
-          test -f requirements.txt
+          test -f /projects/redhat-devspaces/requirements.txt
           python3 -m venv /projects/.venv
           . /projects/.venv/bin/activate
           python -m pip install --upgrade pip wheel setuptools
-          pip install -r requirements.txt
+          pip install -r /projects/redhat-devspaces/requirements.txt
           if ! grep -q "/projects/.venv/bin/activate" ~/.bashrc 2>/dev/null; then
             echo ". /projects/.venv/bin/activate" >> ~/.bashrc
           fi
